[package]
name = "gotron"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.0.15"
rick-and-morty = "0.1.0"
tokio = { version = "1.21.2", features = ["full"] }
tokio-compat-02 = "0.2.0"
warp = "0.3.3"
warp-reverse-proxy = "0.5.0"
